export const COPY = {
  en: {
    nav: ['About', 'Services', 'Work', 'Process', 'Contact'],
    available: 'Available · April 2026',
    headline_1: 'Senior web engineering.',
    headline_accent: 'No buzzwords. Less talk, more shipped.',
    lead: '20+ years building reliable, scalable backends and infrastructure for SaaS, e-commerce and B2B platforms. I work directly with CTOs and founders — no account managers in between.',
    cta_primary: 'Write me →',
    cta_ghost: 'See the work',
    stats: [
      { num: '20', small: '+', lbl: 'Years shipping' },
      { num: '60', small: '+', lbl: 'Production systems' },
      { num: '30k', small: '', lbl: 'DAU on largest project' },
      { num: 'EN/RU', small: '', lbl: 'Bilingual delivery' },
    ],
    clientsEyebrow: 'Trusted by teams at',
    clients: [
      { name: 'anbit', meta: 'IT services · DE', href: 'https://anbit.io' },
      { name: 'Nemerald', meta: 'B2B telecom', href: 'https://nemerald.com' },
      { name: 'Cosmotown', meta: 'ICANN registrar', href: 'https://cosmotown.com' },
      { name: 'Madani Rings', meta: 'Jewelry wholesale', href: 'https://madanirings.com' },
      { name: 'CabinetsBay', meta: 'E-commerce', href: 'https://cabinetsbay.com' },
      { name: 'Pure Bulk', meta: 'E-Commerce', href: 'http://purebulk.com' },
    ],
    aboutEyebrow: '01 · About',
    aboutTitle: 'A senior pair of hands. Twenty years in.',
    aboutBody: [
      "I'm Alex. If your team needs a senior engineer who can own the system end-to-end — from data model to deploy — you're in the right place.",
      "Since 2003 I've shipped backends, infrastructure and full products — from startups to mature platforms. Experience across **e-commerce, fintech, telecom, B2B SaaS and live streaming**. I work directly with CTOs, Heads of Engineering and founders.",
      "My job is to balance speed with quality. **Move too fast** and you ship technical debt that costs you the next quarter. **Move too slow** and you lose momentum. The work is finding the line — and holding it.",
    ],
    aboutSpecs: [
      { k: 'Based', v: 'Remote · CET' },
      { k: 'Since', v: '2003' },
      { k: 'Languages', v: 'EN · RU' },
      { k: 'Stack', v: 'PHP · Node · TS · Postgres' },
      { k: 'Modes', v: 'Contract · Retainer · Lead' },
      { k: 'Booking', v: '4–6 weeks lead time' },
    ],
    servicesEyebrow: '02 · Services',
    servicesTitle: 'Three modes. All hands-on.',
    servicesLead: 'No subcontractors. Direct contact with the person writing the code.',
    services: [
      {
        num: '01', t: 'Web engineering',
        d: 'Backend architecture, APIs and full-stack delivery. Integrations — from payment gateways and e-commerce to GPS navigation and mapping (OSM · OSRM). Systems that hold up under growth.',
        items: ['Backend & API design', 'Payments, e-com & GPS/maps', 'Performance & scaling', 'Refactoring legacy code'],
        stack: 'PHP (Laravel · Symfony) · Node.js · TypeScript · React/Vue',
      },
      {
        num: '02', t: 'Infrastructure',
        d: 'Production environments that don’t page you at 3am. Cloud, Linux, containers, monitoring and observability.',
        items: ['Cloud (AWS · GCP · Azure)', 'Linux server administration', 'Docker · Kubernetes · CI/CD', 'Monitoring & alerting'],
        stack: 'AWS · GCP · Linux · Docker · Kubernetes',
      },
      {
        num: '03', t: 'Project leadership',
        d: 'Scoping, planning, execution. Senior judgment for the awkward middle stretch where projects die.',
        items: ['Discovery & scoping', 'Architecture decisions', 'Code review & QA', 'Tech-debt triage'],
        stack: 'Strategy · Roadmap · Hands-on',
      },
    ],
    compareEyebrow: '03 · With Alex vs. without',
    compareTitle: 'What changes when a senior owns the build.',
    compareLead: 'No magic. Just twenty years of avoiding the same mistakes.',
    compareCols: ['Question', 'Without Alex', 'With Alex'],
    compareRows: [
      ['Architecture decisions', 'Decided by whoever is loudest in standup. Revisited every six months.', 'Decided once, with reasons documented. Holds up under load.'],
      ['Production incidents', 'Discovered by users. Patched on the live server. Logged in Slack.', 'Caught by monitoring. Postmortem written. Won’t happen twice.'],
      ['Onboarding new devs', 'Two weeks of "ask in the channel". Tribal knowledge.', 'README, runbooks, conventions in code. Productive on day three.'],
      ['Vendor / consultant pitches', 'Bought on the demo. Found unfit at integration.', 'Reviewed against your real constraints. Dropped fast if wrong.'],
      ['Tech-debt conversations', 'Avoided until refactor week is requested.', 'Continuous. Logged with cost. Paid down with interest.'],
      ['Code ownership', 'Vendor may show your code in their portfolio or reuse it for other clients.', 'Your code is yours. Not published, not resold, not reused on other engagements.'],
    ],
    workEyebrow: '04 · Selected work',
    workTitle: 'In production. Real users. Real revenue.',
    workLead: 'A few projects where I owned the backend, infrastructure or key modules.',
    work: [
      { meta_l: 'E-commerce · Magento', meta_r: '2018–2024', t: 'Pure Bulk', d: 'Vitamins and supplements e-shop. Backend ownership of catalog, checkout, fulfilment integrations.', img: '/portfolio/purebulk.webp', m: [{ n: '30k', l: 'Daily users' }, { n: '2.4M', l: 'Products served' }], href: 'http://purebulk.com' },
      { meta_l: 'Telecom · B2B SaaS', meta_r: '2022–', t: 'Nemerald', d: 'Business phone system for modern teams. Backend, infrastructure and integrations.', img: '/portfolio/nemerald.webp', m: [{ n: '12+', l: 'Carriers' }, { n: '99.95%', l: 'Uptime SLA' }], href: 'https://nemerald.com' },
      { meta_l: 'Domains · ICANN', meta_r: '2021–', t: 'Cosmotown', d: 'ICANN-accredited registrar. Affordable domain registration, fast checkout pipeline.', img: '/portfolio/cosmotown.webp', m: [{ n: '500+', l: 'TLDs' }, { n: '<400ms', l: 'Search response' }], href: 'https://cosmotown.com' },
      { meta_l: 'IT services · DE', meta_r: '2019–', t: 'anbit GmbH', d: 'Digital engineering partner. Long-running backend & infrastructure mandate.', img: '/portfolio/anbit.webp', m: [{ n: '5y', l: 'Engagement' }, { n: '8', l: 'Major releases' }], href: 'https://anbit.io' },
      { meta_l: 'Live streaming · SaaS', meta_r: '2024–', t: 'StreamFarm', d: 'One-click multistreaming to VK, Telegram, Twitch, YouTube and more. Backend pipeline and stream orchestration.', img: '/portfolio/streamfarm.webp', m: [{ n: '1K+', l: 'Active streamers' }, { n: '99.9%', l: 'Uptime' }], href: 'https://streamfarm.ru' },
      { meta_l: 'Jewelry · wholesale', meta_r: '2017–', t: 'Madani Rings', d: 'Wholesale wedding bands and fashion rings for North-American jewelry retailers — tungsten, ceramic, cobalt, gold. Catalog, dealer accounts and store-locator backend.', img: '/portfolio/madanirings.webp', m: [{ n: '1000+', l: 'SKUs' }, { n: 'US / CA', l: 'Retailers' }], href: 'https://madanirings.com' },
      { meta_l: 'Kitchens · Magento', meta_r: '2021–2023', t: 'CabinetsBay', d: 'Made-to-order kitchen cabinets for the US market. Built from scratch — catalog, configurator, checkout and 3D-design flow.', img: '/portfolio/cabinetsbay.webp', m: [{ n: '1000+', l: 'SKUs' }, { n: 'US', l: 'Market' }], href: 'https://cabinetsbay.com' },
      { meta_l: 'Healthtech · SaaS', meta_r: '2024–', t: 'Medbrain', d: 'Practice management SaaS for German medical clinics — patients, treatment cases, prescriptions, documents, invoicing and the full GOÄ fee catalog. Multi-tenant, EN/DE. In active development.', img: '/portfolio/medbrain.webp', m: [{ n: 'Full GOÄ', l: 'fee catalog' }, { n: 'Multi-tenant', l: 'architecture' }] },
    ],
    processEyebrow: '05 · How an engagement runs',
    processTitle: 'Discovery to handover, transparently.',
    processLead: 'Most projects fit a four-step shape. The unusual ones, we adapt.',
    process: [
      { n: '01', t: 'Discovery brief', d: 'Async written exchange. You describe the system, team, constraints and deadline. I respond in detail.', dur: 'Free · within 1 day' },
      { n: '02', t: 'Scoping & estimate', d: 'A short written proposal: scope, milestones, fixed price or hourly, what could go wrong.', dur: '3–5 working days' },
      { n: '03', t: 'Build & ship', d: 'Weekly demo. Async updates. Code in your repo. No black box.', dur: 'Per scope · ~6–12 weeks typical' },
      { n: '04', t: 'Handover & retainer', d: 'Docs, runbooks, knowledge transfer. Optional retainer for ongoing ownership.', dur: 'On demand' },
    ],
    contactTitle_1: 'Got a system that needs',
    contactTitle_2: 'a senior pair of hands?',
    contactSub: 'I work async — email, LinkedIn or Upwork/Golance message. Reply within one working day. If it’s not a fit, I’ll tell you and point you somewhere better.',
    contactPrimary: 'alexander@sharapov.biz',
    footerLeft: '© 2026 Alexander Sharapov · Senior web engineer & system architect',
    photoName: 'Alexander Sharapov',
    photoRole: 'Senior web engineer · System architect',
    photoBadges: ['Backend', 'Infra', 'Lead'],
    photoSince: 'Shipping since 2003',
  },
  ru: {
    nav: ['Обо мне', 'Услуги', 'Работы', 'Процесс', 'Контакты'],
    available: 'Открыт к проектам · апрель 2026',
    headline_1: 'Веб-инженерия по-взрослому.',
    headline_accent: 'Без воды. Меньше слов — больше дела.',
    lead: 'Больше двадцати лет делаю надёжные бэкенды и инфраструктуру для SaaS, e-commerce и B2B-платформ. Работаю напрямую с CTO и фаундерами — без аккаунт-менеджеров посередине.',
    cta_primary: 'Написать →',
    cta_ghost: 'Посмотреть работы',
    stats: [
      { num: '20', small: '+', lbl: 'лет в продакшене' },
      { num: '60', small: '+', lbl: 'систем в проде' },
      { num: '30k', small: '', lbl: 'DAU у крупнейшего проекта' },
      { num: 'EN/RU', small: '', lbl: 'два языка' },
    ],
    clientsEyebrow: 'Со мной работали команды',
    clients: [
      { name: 'anbit', meta: 'IT-услуги', href: 'https://anbit.io' },
      { name: 'Nemerald', meta: 'B2B телеком', href: 'https://nemerald.com' },
      { name: 'Cosmotown', meta: 'регистратор ICANN', href: 'https://cosmotown.com' },
      { name: 'Madani Rings', meta: 'ювелирный опт', href: 'https://madanirings.com' },
      { name: 'CabinetsBay', meta: 'e-commerce', href: 'https://cabinetsbay.com' },
      { name: 'Pure Bulk', meta: 'E-Commerce', href: 'http://purebulk.com' },
    ],
    aboutEyebrow: '01 · Обо мне',
    aboutTitle: 'Двадцать лет в продакшене. Без украшений.',
    aboutBody: [
      'Привет, я Александр. Если команде нужен старший инженер, который возьмёт систему целиком — от модели данных до деплоя — вам сюда.',
      'С 2003 года делаю бэкенды, инфраструктуру и продукты целиком — от стартапов до зрелых платформ. Опыт в **e-commerce, fintech, телекоме, B2B SaaS и видеостриминге**. Общаюсь напрямую с CTO, руководителями разработки и фаундерами.',
      'Главное в работе — баланс скорости и качества. **Гнать слишком быстро** — копится технический долг, который выстрелит в следующем квартале. **Тянуть слишком долго** — теряется темп. Задача — поймать эту грань и удержаться на ней.',
    ],
    aboutSpecs: [
      { k: 'Где', v: 'удалённо · CET' },
      { k: 'С', v: '2003' },
      { k: 'Языки', v: 'EN · RU' },
      { k: 'Стек', v: 'PHP · Node · TS · Postgres' },
      { k: 'Формат', v: 'контракт · сопровождение · лид' },
      { k: 'Очередь', v: '4–6 недель' },
    ],
    servicesEyebrow: '02 · Услуги',
    servicesTitle: 'Три формата. Везде сам, руками.',
    servicesLead: 'Без субподрядчиков. Прямой контакт с тем, кто пишет код.',
    services: [
      {
        num: '01', t: 'Веб-инженерия',
        d: 'Архитектура бэкенда, API и full-stack-разработка. Интеграции — от платёжных шлюзов и e-commerce до GPS-навигации и картографии (OSM · OSRM). Системы, которые держат рост.',
        items: ['Backend и проектирование API', 'Платежи, e-com и GPS/карты', 'Производительность и масштабирование', 'Рефакторинг легаси-кода'],
        stack: 'PHP (Laravel · Symfony) · Node.js · TypeScript · React/Vue',
      },
      {
        num: '02', t: 'Инфраструктура',
        d: 'Прод, который не будит вас в три ночи. Cloud, Linux, контейнеры, мониторинг и наблюдаемость.',
        items: ['Cloud (AWS · GCP · Azure)', 'Linux-администрирование', 'Docker · Kubernetes · CI/CD', 'Мониторинг и алерты'],
        stack: 'AWS · GCP · Linux · Docker · Kubernetes',
      },
      {
        num: '03', t: 'Ведение проекта',
        d: 'Скоупинг, планирование, исполнение. Зрелый взгляд на трудную середину — там, где умирает большинство проектов.',
        items: ['Discovery и скоупинг', 'Архитектурные решения', 'Code review и QA', 'Технический долг и приоритеты'],
        stack: 'Стратегия · roadmap · реализация',
      },
    ],
    compareEyebrow: '03 · С Александром vs. без',
    compareTitle: 'Что меняется, когда система — в руках старшего инженера.',
    compareLead: 'Никакой магии. Просто двадцать лет опыта — на этих граблях я уже стоял.',
    compareCols: ['Вопрос', 'Без меня', 'Со мной'],
    compareRows: [
      ['Архитектурные решения', 'Принимает тот, кто громче на стендапе. Каждые полгода всё переписывают заново.', 'Принято один раз, причины задокументированы. Держит нагрузку.'],
      ['Инциденты в проде', 'Узнаёте от пользователей. Патчите на живом сервере. Логи теряются в чатах.', 'Ловит мониторинг. Разбор инцидента написан. Дважды не выстрелит.'],
      ['Онбординг разработчиков', 'Две недели «спроси в чате». Знания живут только в головах.', 'README, runbooks, договорённости в коде. На третий день человек уже в деле.'],
      ['Тендеры и подрядчики', 'Покупаете по красивой демке. Несовместимость вылезает на интеграции.', 'Сверяю с вашими реальными ограничениями. Если не подходит — отказываемся быстро.'],
      ['Технический долг', 'Откладывается до «недели рефакторинга», которой не наступает.', 'Считается постоянно. Гасится планомерно — с процентами.'],
      ['Право на код', 'Подрядчик может выложить ваш код в портфолио или переиспользовать на других клиентах.', 'Ваш код принадлежит вам. Не публикуется, не перепродаётся, не идёт в чужие проекты.'],
    ],
    workEyebrow: '04 · Избранные работы',
    workTitle: 'В продакшене. Реальные пользователи. Реальная выручка.',
    workLead: 'Несколько проектов, где я отвечал за бэкенд, инфраструктуру или ключевые модули.',
    work: [
      { meta_l: 'E-commerce · Magento', meta_r: '2018–2024', t: 'Pure Bulk', d: 'Магазин витаминов и БАДов. Отвечал за бэкенд каталога, оформление заказа, интеграции с фулфилментом.', img: '/portfolio/purebulk.webp', m: [{ n: '30k', l: 'DAU' }, { n: '2.4M', l: 'товаров отгружено' }], href: 'http://purebulk.com' },
      { meta_l: 'Телеком · B2B SaaS', meta_r: '2022–', t: 'Nemerald', d: 'Корпоративная телефония для современных команд. Бэкенд, инфраструктура и интеграции.', img: '/portfolio/nemerald.webp', m: [{ n: '12+', l: 'операторов' }, { n: '99,95%', l: 'uptime SLA' }], href: 'https://nemerald.com' },
      { meta_l: 'Домены · ICANN', meta_r: '2021–', t: 'Cosmotown', d: 'Регистратор с аккредитацией ICANN. Регистрация доменов, быстрое оформление.', img: '/portfolio/cosmotown.webp', m: [{ n: '500+', l: 'TLD' }, { n: '<400 мс', l: 'отклик поиска' }], href: 'https://cosmotown.com' },
      { meta_l: 'IT-услуги · DE', meta_r: '2019–', t: 'anbit GmbH', d: 'Технический партнёр в Германии. Многолетнее сотрудничество по бэкенду и инфраструктуре.', img: '/portfolio/anbit.webp', m: [{ n: '5 лет', l: 'сотрудничества' }, { n: '8', l: 'крупных релизов' }], href: 'https://anbit.io' },
      { meta_l: 'Видеостриминг · SaaS', meta_r: '2024–', t: 'StreamFarm', d: 'Мультистриминг в один клик: VK, Telegram, Twitch, YouTube и другие площадки. Бэкенд и оркестрация трансляций.', img: '/portfolio/streamfarm.webp', m: [{ n: '1k+', l: 'активных стримеров' }, { n: '99,9%', l: 'uptime' }], href: 'https://streamfarm.ru' },
      { meta_l: 'Ювелирка · опт', meta_r: '2017–', t: 'Madani Rings', d: 'Оптовая платформа обручальных колец и украшений для североамериканских ювелирных ритейлеров — вольфрам, керамика, кобальт, золото. Бэкенд каталога, дилерских аккаунтов и поиска магазинов.', img: '/portfolio/madanirings.webp', m: [{ n: '1000+', l: 'позиций' }, { n: 'US / CA', l: 'ритейлеры' }], href: 'https://madanirings.com' },
      { meta_l: 'Кухни · Magento', meta_r: '2021–2023', t: 'CabinetsBay', d: 'Магазин кухонь на заказ для рынка США. Разработка с нуля — каталог, конфигуратор, оформление заказа и 3D-дизайн.', img: '/portfolio/cabinetsbay.webp', m: [{ n: '1000+', l: 'позиций' }, { n: 'US', l: 'рынок' }], href: 'https://cabinetsbay.com' },
      { meta_l: 'Медтех · SaaS', meta_r: '2024–', t: 'Medbrain', d: 'SaaS для управления частными клиниками в Германии: пациенты, случаи лечения, рецепты, документы, выставление счетов и полный каталог GOÄ. Multi-tenant, EN/DE. В активной разработке.', img: '/portfolio/medbrain.webp', m: [{ n: 'Полный GOÄ', l: 'каталог' }, { n: 'Multi-tenant', l: 'архитектура' }] },
    ],
    processEyebrow: '05 · Как идёт сотрудничество',
    processTitle: 'От первого письма до передачи. Прозрачно.',
    processLead: 'Большинство проектов укладывается в четыре шага. Нестандартные — подстраиваем.',
    process: [
      { n: '01', t: 'Знакомство и бриф', d: 'Вы описываете систему, команду, ограничения и сроки — я подробно отвечаю.', dur: 'бесплатно · в течение дня' },
      { n: '02', t: 'Скоупинг и оценка', d: 'Короткое письменное предложение: объём, вехи, фикс или почасовка, риски.', dur: '3–5 рабочих дней' },
      { n: '03', t: 'Разработка и релиз', d: 'Демо раз в неделю. Регулярные апдейты. Код в вашем репозитории. Без чёрного ящика.', dur: 'по объёму · обычно 6–12 недель' },
      { n: '04', t: 'Передача и сопровождение', d: 'Документация, runbooks, передача знаний. По желанию — договор на постоянное сопровождение.', dur: 'по запросу' },
    ],
    contactTitle_1: 'Есть система,',
    contactTitle_2: 'которой нужен старший инженер?',
    contactSub: 'Работаю асинхронно — почта, LinkedIn или сообщение на Upwork/Golance. Отвечаю в течение рабочего дня. Если не подойду — скажу прямо и подскажу, к кому обратиться.',
    contactPrimary: 'alexander@sharapov.biz',
    footerLeft: '© 2026 Александр Шарапов · старший веб-инженер и системный архитектор',
    photoName: 'Александр Шарапов',
    photoRole: 'старший веб-инженер · системный архитектор',
    photoBadges: ['Бэкенд', 'Инфра', 'Лид'],
    photoSince: 'В продакшене с 2003',
  },
};

export const SOCIAL = [
  { k: 'Email',    v: 'alexander@sharapov.biz', href: 'mailto:alexander@sharapov.biz' },
  { k: 'LinkedIn', v: 'in/sharapovalexander',   href: 'https://www.linkedin.com/in/sharapovalexander' },
  { k: 'Upwork',   v: 'freelancers/sharapov',   href: 'https://www.upwork.com/freelancers/sharapov' },
  { k: 'GoLance',  v: 'alexander.sharapov',     href: 'https://golance.com/freelancer/alexander.sharapov' },
  { k: 'GitHub',   v: 'sharapov-outsource',     href: 'https://github.com/sharapov-outsource' },
];
